### ISSUE TITLE
_onBackspacePress这个函数怎么写的，百度谷歌了半天没有找到删除textInput内容的解决方案

### ISSUE THREAD

**Issue by cloudsafe** [xiewang/react-native-emoticons#1]
_onBackspacePress这个函数怎么写的，百度谷歌了半天没有找到删除textInput内容的解决方案

**Comment by xiewang** [comment]
@cloudsafe 你可以参考我的这个写法，原理很简单
https://github.com/ShareTechChina/AppReact/blob/master/app/pages/comment/index.js#L116

**Comment by cloudsafe** [comment]
@xiewang thx昨天用js截取字符串的方式搞了半天，emoji删除有bug看了下你发的这个，还是这个简单。

**Comment by cloudsafe** [comment]
emoji数据源中，如果要去掉某一个应该怎么搞，比如有个港Du的旗子得去掉。。对emoji数据源不熟悉，这几天精力主要放在即时通讯上了。。web即时通讯与app的刚实现互发消息。。。

**Comment by xiewang** [comment]
@cloudsafe 属性 concise={true} 开启精简模式，这是我自己挑选的一些emoji 
[例图](https://github.com/xiewang/react-native-emoticons/blob/master/docs/sample2.png)

后续版本我会考虑允许用户自选的emoji表情list传进来

你要是着急用，可以手动修改这里：https://github.com/xiewang/react-native-emoticons/blob/master/index.js#L31
数组里每个值是emoji的short name（https://github.com/iamcal/emoji-data）

**Comment by cloudsafe** [comment]
@xiewang 我把concise设置fasle了，我去找下那个吧它手动删除了吧。非常感谢。
