### ISSUE TITLE
undefined is not an object(evaluating 'ViewPropTypes.style') 

### ISSUE THREAD

**Issue by didil** [xiewang/react-native-emoticons#2]
getting this error when importing Emoticons as described in readme file,

react native 0.42

screenshot : 

![screen shot 2017-06-08 at 14 21 36](https://user-images.githubusercontent.com/1284255/26928280-d2f5b434-4c55-11e7-8bfa-4d2c9fda03a2.png)

partial stack trace : 

2017-06-08 14:17:01.743 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Exception '-[NSNull integerValue]: unrecognized selector sent to instance 0x1034d0180' was thrown while invoking updateExceptionMessage on target ExceptionsManager with params (
    "undefined is not an object (evaluating 'ViewPropTypes.style')",
        (
                {
            column = 28;
            file = "node_modules/react-native-emoticons/node_modules/react-native-scrollable-tab-view/DefaultTabBar.js";
            lineNumber = 20;
            methodName = "<unknown>";
        },
                {
            column = 12;
            file = "node_modules/react-native/packager/src/Resolver/polyfills/require.js";
            lineNumber = 171;
            methodName = loadModuleImplementation;
        },
                {
            column = 30;
            file = "node_modules/react-native-emoticons/node_modules/react-native-scrollable-tab-view/index.js";
            lineNumber = 20;
            methodName = "<unknown>";
        },
                {
            column = 12;
            file = "node_modules/react-native/packager/src/Resolver/polyfills/require.js";
            lineNumber = 171;
            methodName = loadModuleImplementation;
        },
                {
            column = 0;
            file = "node_modules/react-native-emoticons/index.js";
            lineNumber = 18;
            methodName = "<unknown>";
        },
                {
            column = 12;
            file = "node_modules/react-native/packager/src/Resolver/polyfills/require.js";
            lineNumber = 171;
            methodName = loadModuleImplementation;
        },

**Comment by xiewang** [comment]
It is incompatibility problem between RN and  react-native-scrollable-tab-view
This solution might be helpful: 
https://github.com/skv-headless/react-native-scrollable-tab-view/issues/634

**Comment by didil** [comment]
are you suggesting we upgrade to RN 0.45 ?

**Comment by xiewang** [comment]
@didil or you can reduce your react-native-scrollable-tab-view @0.7.0

**Comment by didil** [comment]
ok upgrading to 0.45 fixed the issue, thanks !
