### ISSUE TITLE
'this.props.style' Unable to override style

### ISSUE THREAD

**Issue by Maple13** [xiewang/react-native-emoticons#26]
`this.props.style` can only add styles, not override styles, I hope I can change them.
![image](https://user-images.githubusercontent.com/11918457/44443154-e400b180-a608-11e8-94d3-d39ea7ceb663.png)
I hope I can put it at the end of the style array.

(ps: Chinese : 传递的 props 属性 `style` 只能新增样式属性, 而覆盖不了, 因为它位于样式数组的第一个, 希望能修改一下把它放在样式数组的最后, 这样可以重写/覆盖需要的样式, 谢谢!)

**Comment by xiewang** [comment]
是的，谢谢

**Comment by Maple13** [comment]
@xiewang 
那您近期有时间能更新一下 `npmjs.com` 的包吗? 因为我项目需要它, 而现在我不得不临时在本地修改, 最后, 祝好!

**Comment by xiewang** [comment]
@Maple13 done

**Comment by Maple13** [comment]
@xiewang 
thanks
