### ISSUE TITLE
我发现我这边android下，表情全城黑白的了。

### ISSUE THREAD

**Issue by cloudsafe** [xiewang/react-native-emoticons#3]
我发现我这边android下，表情全成黑白的了，iphone正常。
昨天更新了次所有包括rn版本，貌似你这个也升级了（手机忘带，明天确认下手机上的旧版本app是否也是黑白）。
你看下你那边是否是黑白色。（今晚貌似rn升级到0.45了又，新建项目都运行不起来）

**Comment by xiewang** [comment]
你install最新的版本再试试呢？
