### ISSUE TITLE
android empty emoticons area 

### ISSUE THREAD

**Issue by didil** [xiewang/react-native-emoticons#4]
Hi

so the emoticons component works for us on iOS , but when testing on android we get a blank emoticons area like on this screenshot below (We're using RN 0.45.1 , android 6.0 platform 23) :

![screen shot 2017-06-12 at 15 43 26](https://user-images.githubusercontent.com/1284255/27036798-5048aad0-4f86-11e7-8ff1-730c5dbf2f4a.png)

**Comment by xiewang** [comment]
Install the latest version of react-native-emoticons.
Let me know that if this issue still exists!

**Comment by didil** [comment]
@xiewang just tried with react-native-emoticons 1.0.5 . still getting a blank screen for android

**Comment by xiewang** [comment]
Just using a tricky solution for android(@1.0.6), not the best, I will replace this with better ways.

**Comment by didil** [comment]
thanks, its working with 1.0.6 !
