### ISSUE TITLE
哥们，我又来了，不知道算不算bug，android下，concise设置为false，会巨卡，会影响整个component的执行速度。

### ISSUE THREAD

**Issue by cloudsafe** [xiewang/react-native-emoticons#5]
debug下测试的巨卡，release下还没测。

**Comment by xiewang** [comment]
@cloudsafe 嗯，非concise下数据量很大，还没做过优化。
我想想解决方法

**Comment by xiewang** [comment]
Sorry late for this. if you still on and have have time on this, try the latest version(@1.0.7) and add  a props to the components. The props is asyncRender, and set it true on android. Let me knew that if this solution is valid.
Thanks a lot

`<Emoticons`
		` onEmoticonPress={this._onEmoticonPress.bind(this)}`
		` onBackspacePress={this._onBackspacePress.bind(this)}`
		` show={this.state.showEmoticons}`
		 `concise={true}`
		` showHistoryBar={true}`
		 `showPlusBar={true}`
                 `asyncRender={true}`
    ` />
`
