### ISSUE TITLE
transparent emoticons

### ISSUE THREAD

**Issue by FarhounYoussef** [xiewang/react-native-emoticons#7]
![2017-08-02 09 33 45](https://user-images.githubusercontent.com/18389045/28865373-90221930-7767-11e7-99fc-1afa6782bf47.png)

By default alpha in text color is set to 0.7 you have to overrind it by  color: '#rgba(0,0,0,1)'

this issue can be solved with:
- adding color: '#rgba(0,0,0,1)' in emoji style (line 37 in ./style.js)
- replacing: {fontSize: 25} by styles.emoji in text style (line 88 in ./tab.js)

**Comment by xiewang** [comment]
thanks, I'll fix that
